Repository Piotr45/cmos-preprocessor, pull requests merged in 2023-01, with the labels that each got.

#26 Fix train set size in one split
  neural-network/scripts/prepare_dataset_pipeline.py
Labels: bug

#29 Change response condition
  neural-network/scripts/prepare_dataset.py
Labels: enhancement

#31 Add random state to train test splits
  neural-network/scripts/prepare_dataset_pipeline.py
Labels: enhancement

#33 27 optimize hyperparameters
  .gitignore
  neural-network/scripts/optimize.py
Labels: enhancement

#36 Removed comments
  preprocessor/components/AXON.sp
  preprocessor/components/CMRR.sp
  preprocessor/components/DENDRITE.sp
  preprocessor/components/DIODE.sp
  preprocessor/grid/dendrite_sim.sp
  preprocessor/grid/grid.gr
Labels: documentation

#37 3 implement scripts to generate preprocessors structure
  preprocessor/parser/model_parser.py
  preprocessor/parser/parse_model.py
  preprocessor/preprocessor.sp
  resources/grid.txt
Labels: enhancement

#40 Fix neural network parser
  preprocessor/parser/model_parser.py
Labels: bug

#41 Add handling empty scaler
  neural-network/scripts/prepare_dataset_pipeline.py
Labels: enhancement
